name: Publish project to Maven repository
# Publish manually
on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)